name: Build & Push Template

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string
      ecr_repo:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      gitops_repo:
        required: true
        type: string
      values_file:
        required: true
        type: string
      build_system:
        required: false
        default: gradle
        type: string   # gradle | maven | node
      jdk_version:
        required: false
        default: '17'
        type: string
      node_version:
        required: false
        default: '20'
        type: string

permissions:
  contents: read
  id-token: none   # OIDC for AWS

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ inputs.aws_region }}
      ECR_REPO:   ${{ inputs.ecr_repo }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Build env (Gradle/Maven/Node) ----------
      - name: Set up JDK
        if: ${{ inputs.build_system == 'gradle' || inputs.build_system == 'maven' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}

      - name: Cache Gradle
        if: ${{ inputs.build_system == 'gradle' }}
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.context }}/.gradle/caches
            ${{ inputs.context }}/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles(format('{0}/**/*.gradle*', inputs.context), format('{0}/gradle-wrapper.properties', inputs.context)) }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build (Gradle)
        if: ${{ inputs.build_system == 'gradle' }}
        working-directory: ${{ inputs.context }}
        run: ./gradlew clean test bootJar --no-daemon

      - name: Cache Maven
        if: ${{ inputs.build_system == 'maven' }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles(format('{0}/**/pom.xml', inputs.context)) }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build (Maven)
        if: ${{ inputs.build_system == 'maven' }}
        working-directory: ${{ inputs.context }}
        run: mvn -B -U -e -DskipTests=false clean package

      - name: Setup Node
        if: ${{ inputs.build_system == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      - name: Build (Node)
        if: ${{ inputs.build_system == 'node' }}
        working-directory: ${{ inputs.context }}
        run: |
          npm ci
          npm test --if-present
          npm run build --if-present

      # ---------- AWS & ECR ----------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GH_ACTIONS_ROLE_FOR_ECR }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG -f "${{ inputs.dockerfile }}" "${{ inputs.context }}"
          docker push $ECR_REGISTRY/${ECR_REPO}:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_REPO=$ECR_REGISTRY/${ECR_REPO}" >> $GITHUB_ENV

      # ---------- Notify GitOps ----------
      # - name: Trigger GitOps (repository_dispatch)
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.GITOPS_PAT }}
      #     repository: ${{ inputs.gitops_repo }}
      #     event-type: app_release
      #     client-payload: |
      #       {
      #         "app_name":   "${{ inputs.app_name }}",
      #         "repository": "${{ github.repository }}",
      #         "image_repo": "${{ env.IMAGE_REPO }}",
      #         "image_tag":  "${{ env.IMAGE_TAG }}",
      #         "values_file":"${{ inputs.values_file }}"
      #       }
